language: scala

matrix:
  include:
    # scala 2.10
    - jdk: oraclejdk8
      scala: 2.10.5
      env: SCALAZ_STREAM_VERSION=0.7.3a
    - jdk: oraclejdk8
      scala: 2.10.5
      env: SCALAZ_STREAM_VERSION=0.8.1a
    # scala 2.11
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_STREAM_VERSION=0.8.1a
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_STREAM_VERSION=0.7.3a

sudo: required

env:
  global:
    - secure: "LAL5EEsTd3SC764Og0qVjwZWdh6MZHW+XjjdkzhQVtHEjFOTkNn0WKtkb5Itrh+6qzdjvZBX8TQ1T+RMrqOCKP01Svh4uizBS6/ucr+KtC/Rgfd+G4YZ3OFXGer0WRlvrON3ZrZ8QAtU1wVZ8oQ+XHv+jlEcRBt1Gn+FAxttwV0FP/tv3+UjwSSIWkIik8MeAFQtQtcygk/bweoqK6EQs2/at2lRVhiwcOVtnqR9snWh34FSVYSur4MqzmukO5Na+vk5CGYVFLK+UzxL48E8oxOQl4W3qnkEHf+66fy2zqBJ7qZYrN/7WJRa4l1GjQvSrX6KUSt3I+HxwX2at16QazYHAoQDEvL1n746hGbavrlL94XgRl9Ti28DPO2n+4iIUTiIYCXSFcI4EtIXF4BG+0MhRAskHVhTusMyRmd2QAYqu1PLQNPuHGYWOlHwuGxfh60eygLH3WOLWcEY8Ajg4BcC3FMYYLqAdbJ+6Mhr9EIOXTDSEDtgkjeuIFB6WmxvZxEL7nQ3/wC77ZtGSMpfXgc+H4mUuAV8JR2Daz7FhxRUbYeWoUiMpiiWFu3BsYqY7RMjtp2Z0OPFFQ6PbF3R0i3GMylqboAjBzwC83wDApW7i41fh4ceKjD7xgAmh8a3P8GvlA9NX/30NMTRcwzf7REaJxlulXHoZX5gfabgcIw="

install:
  - mkdir $HOME/.bintray/
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then echo $BINTRAY_CREDENTIALS | base64 --decode > $HOME/.bintray/.credentials; fi"

before_script:
  - git config --global user.email "oss@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git fetch -q --unshallow
  - git checkout -qf $TRAVIS_BRANCH

script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION 'release with-defaults'; else sbt ++$TRAVIS_SCALA_VERSION test; fi"

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
