language: scala

matrix:
  include:
    # scala 2.10
    - jdk: oraclejdk8
      scala: 2.10.5
      env: SCALAZ_STREAM_VERSION=0.7.3a
    # - jdk: oraclejdk8
    #   scala: 2.10.5
    #   env: SCALAZ_STREAM_VERSION=0.8.1a
    # # scala 2.11
    # - jdk: oraclejdk8
    #   scala: 2.11.8
    #   env: SCALAZ_STREAM_VERSION=0.8.1a
    # - jdk: oraclejdk8
    #   scala: 2.11.8
    #   env: SCALAZ_STREAM_VERSION=0.7.3a

sudo: required

env:
  global:
    - secure: "YrtaO+wGrbWIiiZNjAZsKIKxUyG5eeF5e7TLc7CgkUeSbHrdYwUr3K8mEkkBMP9R+sffqBoyg5f4pfv84BxSdg2ZB9tp7TZ6uKJJkaT7XLY8r7crltrn9EFh0eUqmQzSQ1I3H6ULo/ncMNuVJH+Ha1sWz/80xzGuNuBJ+1SpbxP/q5fQRdP6Afr3jXfPhjQtFyyq+BOfW/7IvgvNclR9xFh/GOI0tnqvikQOIpyPxqgxXPa2urbWXqud2iQ6ekw4ny4U46OMQBPLdmLp482ULk8cxibeEHgaVTCASTbuxd5h46PGSOMGXj97x+rAxfP5lUKUacuxdmfjiH0wiIKvxJNECOk9ZnxuLX/85ARLZ+NCqumI6jD9kyt3shty7YT3wZA/y3xR7TouJ70hy/zHGepZ+b9fGCYxrlbmox4WKNuVTkPkMD/4+4kEbxDSSnpgSVbpWF+1xl42N7Cwmc8pjPmYOvrv3wSvI8GKBwgIZ/CWSeLfSrWup1olfV5MJiR0ZYLrhXM+i/Frb0CBz8Ji3ckhg2e5zaYh61xkqkJBXi0Gp8IRkuGiIpTN7O+wRSy8lBEkBAHLO65EyxhvJTpcII30VHKPR1+/JDxOHCPHWXr5qlX570KEBxO4+QycuhLJjNdZS68oglij35LB8kx13mblIF0Xp2YXOreQkqEmQXQ="

install:
  - mkdir $HOME/.bintray/
  - echo $BINTRAY_CREDENTIALS
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then echo $BINTRAY_CREDENTIALS | base64 --decode > $HOME/.bintray/.credentials; fi"

before_script:
  - git config --global user.email "oss@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git fetch -q --unshallow
  - git checkout -qf $TRAVIS_BRANCH

script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION 'release with-defaults'; else sbt ++$TRAVIS_SCALA_VERSION test; fi"

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
