language: scala

matrix:
  include:
    # scala 2.10
    - jdk: oraclejdk8
      scala: 2.10.5
      env: SCALAZ_STREAM_VERSION=0.7.3a
    - jdk: oraclejdk8
      scala: 2.10.5
      env: SCALAZ_STREAM_VERSION=0.8.1a
    # scala 2.11
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_STREAM_VERSION=0.8.1a
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_STREAM_VERSION=0.7.3a

sudo: required

branches:
  only:
    - master

env:
  global:
    # BINTRAY_USER
    - secure: "Vjjrs8GpRYkCTRlR68OoGWD5L8LAZARasL4qZnWCYlVXU5Yc50pPwAnsjQR3+QBAFV1+YEEGdTSkhdxzvJgL9tbdnP+jSQ8JdFk/tvEbhM4EgjJemyVnTPYHFX1UfvvJIaGXEpMwGdjTGHZeqQBqdLL0cboc0Q/LrTAs3fBa7sk="
    # BINTRAY_TOKEN
    - secure: "CvT0GG1yLWMC8y9Wd/LG5Ww7xXJfOaQDxIJAw8Cg+lzJzaHz3AlGkW4KlOswVJEcfNplUx1YJK2u6GDoAFLgdi/m4/D6b+WkJeAD0C2gj3s31WiCgcpqEhK5iSHj8219p1DU2gTmqd4o7iOw76vvUvj3vxd79I1ikZXikzjLcfc="

install:
  - mkdir $HOME/.bintray/
  - >
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      echo realm = Bintray API Realm > $HOME/.bintray/.credentials
      echo host = api.bintray.com >> $HOME/.bintray/.credentials
      echo user = ${BINTRAY_USER} >> $HOME/.bintray/.credentials
      echo password = ${BINTRAY_TOKEN} >> $HOME/.bintray/.credentials
    fi

before_script:
  - git config --global user.email "oss@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git fetch -q --unshallow
  - git checkout -qf $TRAVIS_BRANCH

script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION 'release with-defaults'; else sbt ++$TRAVIS_SCALA_VERSION test; fi"

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
